name: Build and Deploy to EKS (Fargate)

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: 2048-game
  ECR_REGISTRY: docker.io
  DEPLOYMENT_FILE: k8s/deployment.yaml
  NAMESPACE: game-2048

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ github.sha }} .

    - name: Scan Docker Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ github.sha }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ github.sha }}

    - name: Update image tag in deployment.yaml
      run: |
        sed -i "s|victorwasonga/game-2048:.*|${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ github.sha }}|g" $DEPLOYMENT_FILE

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name serverless-game-cluster

    - name: Deploy Updated Deployment Only
      run: kubectl apply -f $DEPLOYMENT_FILE -n $NAMESPACE
