name: Build, Scan, Push, and Deploy

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE: victorwasonga/game-2048-eks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git commit hash
        id: vars
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE:$IMAGE_TAG .

      - name: Scan image using Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}

      - name: Push image to Docker Hub
        run: |
          docker push $DOCKER_IMAGE:$IMAGE_TAG

      - name: Update Kubernetes deployment
        run: |
          sed -i "s|image:.*|image: $DOCKER_IMAGE:$IMAGE_TAG|g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml -n game-2048
