name: CI/CD Pipeline for 2048 Game

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t victorwasonga/game-2048-eks:${{ github.sha }} .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push victorwasonga/game-2048-eks:${{ github.sha }}

      # Step 5: Scan image with Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: victorwasonga/game-2048-eks:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'

      # Step 6: Configure AWS credentials
      - name: Configure AWS credentials for EKS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 7: Update kubeconfig for EKS
      - name: Update kubeconfig for EKS cluster
        run: aws eks update-kubeconfig --name serverless-game-cluster --region us-east-1

      # Step 8: Update deployment image tag
      - name: Update image in deployment.yaml
        run: |
          sed -i "s|victorwasonga/game-2048:latest|victorwasonga/game-2048-eks:${{ github.sha }}|g" k8s/deployment.yaml

      # Step 9: Deploy to EKS
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
