name: Deploy 2048 Game App to EKS with Fargate

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  DOCKERHUB_USERNAME: victorwasonga
  DOCKERHUB_REPO: game-2048-eks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker image tag
        id: vars
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.14.0
        with:
          image-ref: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '0'

      - name: Push image to Docker Hub
        run: |
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/game-2048-deployment game-2048=$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG -n game-2048
